export interface ProblemTemplate {
  id: string;
  text: string;
  answerPrompt: string;
  formula: (vars: Record<string, number>) => number;
  ranges: Record<string, [number, number]>;
}

export type Difficulty = 'normal' | 'advanced' | 'profi';

export const templates: Record<Difficulty, ProblemTemplate[]> = {
  normal: [
    // --- 1. Einkaufen: A * B + C (Punkt vor Strich) ---
    { id: 'n1', text: 'Du kaufst {n} Hefte für die Schule. Jedes Heft kostet {a} Fr. Dazu kaufst du noch einen Radiergummi für {b} Fr. Wie viel musst du an der Kasse bezahlen?', answerPrompt: 'Gesamtkosten:', formula: (v) => v.n * v.a + v.b, ranges: { n: [2, 6], a: [2, 5], b: [1, 3] } },
    { id: 'n2', text: 'Für den Werkunterricht werden {n} Packungen Nägel bestellt. Eine Packung kostet {a} Fr. Der Versand für die gesamte Bestellung kostet pauschal {b} Fr. Wie hoch ist der Rechnungsbetrag?', answerPrompt: 'Rechnungsbetrag:', formula: (v) => v.n * v.a + v.b, ranges: { n: [3, 8], a: [4, 8], b: [5, 10] } },
    { id: 'n3', text: 'Lisa spart für ein neues Spiel. Sie legt {n} Wochen lang jeweils {a} Fr. zur Seite. In ihrem Sparschwein waren vorher schon {b} Fr. Wie viel Geld hat sie jetzt insgesamt?', answerPrompt: 'Gespartes:', formula: (v) => v.n * v.a + v.b, ranges: { n: [4, 10], a: [2, 5], b: [10, 20] } },
    { id: 'n4', text: 'Ein Bauer verkauft {n} Kisten Kartoffeln. Pro Kiste bekommt er {a} Fr. Für die Lieferung berechnet er dem Kunden zusätzlich {b} Fr. Wie viel nimmt er insgesamt ein?', answerPrompt: 'Einnahmen:', formula: (v) => v.n * v.a + v.b, ranges: { n: [5, 12], a: [8, 12], b: [10, 15] } },
    { id: 'n5', text: 'Auf einem Parkplatz stehen {n} Reihen mit Autos. In jeder Reihe parken genau {a} Fahrzeuge. Ganz vorne steht noch ein einzelnes Auto ({b}=1). Wie viele Autos sind es insgesamt?', answerPrompt: 'Anzahl Autos:', formula: (v) => v.n * v.a + v.b, ranges: { n: [4, 8], a: [6, 10], b: [1, 1] } },
    { id: 'n6', text: 'Du backst {n} Bleche mit Plätzchen. Auf jedes Blech passen {a} Stück. Am Ende machst du aus dem Restteig noch {b} Plätzchen extra. Wie viele hast du insgesamt gebacken?', answerPrompt: 'Anzahl Plätzchen:', formula: (v) => v.n * v.a + v.b, ranges: { n: [2, 5], a: [10, 15], b: [3, 8] } },
    { id: 'n7', text: 'Ein Abo für eine Zeitschrift kostet {a} Fr. pro Monat. Die einmalige Anmeldegebühr beträgt {b} Fr. Was kostet das Abo für insgesamt {n} Monate?', answerPrompt: 'Gesamtkosten:', formula: (v) => v.n * v.a + v.b, ranges: { a: [5, 10], b: [10, 20], n: [6, 12] } },
    { id: 'n8', text: 'In einer Turnhalle werden {n} Bänke aufgestellt. Auf jede Bank passen {a} Kinder. {b} Kinder müssen leider auf dem Boden sitzen. Wie viele Kinder sind insgesamt in der Halle?', answerPrompt: 'Anzahl Kinder:', formula: (v) => v.n * v.a + v.b, ranges: { n: [3, 6], a: [4, 6], b: [2, 10] } },
    { id: 'n9', text: 'Ein Handytarif kostet {a} Rappen pro Minute. Du telefonierst {n} Minuten lang. Die einmalige Verbindungsgebühr beträgt {b} Rappen. Was kostet das Gespräch?', answerPrompt: 'Kosten (Rp):', formula: (v) => v.n * v.a + v.b, ranges: { a: [5, 15], n: [5, 20], b: [10, 20] } },
    { id: 'n10', text: 'Der Eintritt in den Park kostet {a} Fr. pro Person. Es gehen {n} Personen hinein. Dazu kaufen sie gemeinsam eine Gruppenkarte für {b} Fr. Was zahlen sie zusammen?', answerPrompt: 'Summe:', formula: (v) => v.n * v.a + v.b, ranges: { a: [8, 15], n: [3, 8], b: [5, 10] } },

    // --- 2. Rückgeld: A - B * C ---
    { id: 'n11', text: 'Du hast {a} Fr. Taschengeld bekommen. Du kaufst dir davon {n} Packungen Sammelkarten für je {b} Fr. Wie viel Geld hast du danach noch übrig?', answerPrompt: 'Restgeld:', formula: (v) => v.a - v.n * v.b, ranges: { a: [20, 50], n: [3, 5], b: [2, 4] } },
    { id: 'n12', text: 'Ein Wassertank ist mit {a} Litern gefüllt. Jede Stunde fließen {b} Liter ab. Das passiert {n} Stunden lang. Wie viel Wasser ist am Ende noch im Tank?', answerPrompt: 'Restwasser:', formula: (v) => v.a - v.n * v.b, ranges: { a: [100, 200], b: [5, 10], n: [4, 8] } },
    { id: 'n13', text: 'Auf einer Rolle sind {a} Meter Stoff. Die Schneiderin schneidet {n} Stücke von je {b} Metern ab. Wie viel Stoff ist noch auf der Rolle?', answerPrompt: 'Reststoff:', formula: (v) => v.a - v.n * v.b, ranges: { a: [20, 50], n: [2, 5], b: [2, 4] } },
    { id: 'n14', text: 'In der Kasse liegen {a} Fr. Der Kassierer gibt {n} Kunden je {b} Fr. Wechselgeld zurück. Wie viel Geld ist danach noch in der Kasse?', answerPrompt: 'Kassenbestand:', formula: (v) => v.a - v.n * v.b, ranges: { a: [50, 100], n: [3, 6], b: [2, 5] } },
    { id: 'n15', text: 'Ein Buch hat {a} Seiten. Du liest {n} Tage lang jeden Tag {b} Seiten. Wie viele Seiten hast du noch vor dir?', answerPrompt: 'Verbleibende Seiten:', formula: (v) => v.a - v.n * v.b, ranges: { a: [150, 300], n: [5, 10], b: [10, 15] } },
    { id: 'n16', text: 'Der Akku hat {a} Prozent Ladung. Pro Stunde Video schauen verlierst du {b} Prozent. Du schaust {n} Stunden lang Videos. Wie voll ist der Akku noch?', answerPrompt: 'Akku-Ladung:', formula: (v) => v.a - v.n * v.b, ranges: { a: [80, 100], b: [10, 15], n: [2, 4] } },
    { id: 'n17', text: 'Es stehen {a} Stühle im Saal. {n} Reihen mit je {b} Stühlen werden für die Reinigung entfernt. Wie viele Stühle stehen noch im Saal?', answerPrompt: 'Anzahl Stühle:', formula: (v) => v.a - v.n * v.b, ranges: { a: [100, 200], n: [4, 8], b: [5, 10] } },
    { id: 'n18', text: 'Du hast einen Gutschein über {a} Fr. Du kaufst {n} Musik-Downloads für je {b} Fr. Wie viel ist der Gutschein jetzt noch wert?', answerPrompt: 'Restwert:', formula: (v) => v.a - v.n * v.b, ranges: { a: [30, 50], n: [5, 10], b: [1, 3] } },
    { id: 'n19', text: 'Ein Vorrat von {a} kg Äpfeln liegt im Keller. Jede Woche werden {b} kg gegessen. Wie viel ist nach {n} Wochen noch da?', answerPrompt: 'Vorrat:', formula: (v) => v.a - v.n * v.b, ranges: { a: [50, 100], b: [3, 5], n: [4, 8] } },
    { id: 'n20', text: 'Die Temperatur betrug {a} Grad. Sie sinkt {n} Stunden lang um je {b} Grad pro Stunde. Wie warm ist es jetzt?', answerPrompt: 'Temperatur:', formula: (v) => v.a - v.n * v.b, ranges: { a: [20, 30], n: [2, 5], b: [2, 4] } },

    // --- 3. Klammerrechnung: (A + B) * C ---
    { id: 'n21', text: 'Eine Familie mit {n} Personen geht ins Kino. Ein Ticket kostet {a} Fr. und eine Tüte Popcorn kostet {b} Fr. Jede Person kauft beides. Was kostet der Abend insgesamt?', answerPrompt: 'Gesamtkosten:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [3, 6], a: [12, 16], b: [5, 8] } },
    { id: 'n22', text: 'Du packst {n} Geschenktüten für deine Party. In jede Tüte kommen {a} Bonbons und {b} Lollis. Wie viele Süßigkeiten brauchst du insgesamt?', answerPrompt: 'Anzahl Süßigkeiten:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [4, 8], a: [3, 6], b: [2, 4] } },
    { id: 'n23', text: 'Ein Menü besteht aus einem Burger für {a} Fr. und Pommes für {b} Fr. Es bestellen {n} Gäste dieses Menü. Wie viel nimmt das Restaurant ein?', answerPrompt: 'Einnahmen:', formula: (v) => v.n * (v.a + v.b), ranges: { a: [8, 12], b: [4, 6], n: [3, 10] } },
    { id: 'n24', text: 'Im Garten werden {n} Beete angelegt. In jedes Beet kommen {a} Tulpen und {b} Narzissen. Wie viele Blumenzwiebeln werden insgesamt gepflanzt?', answerPrompt: 'Gesamtanzahl:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [3, 6], a: [10, 15], b: [5, 10] } },
    { id: 'n25', text: 'Für ein Bastelprojekt brauchen {n} Schüler Material. Jeder bekommt {a} Blatt rotes Papier und {b} Blatt blaues Papier. Wie viele Blätter sind das insgesamt?', answerPrompt: 'Papierbögen:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [10, 20], a: [2, 4], b: [2, 4] } },
    { id: 'n26', text: 'Ein Möbelhaus liefert {n} Stühle aus. Jeder Stuhl hat {a} Holzbeine und {b} Armlehnen. Wie viele Einzelteile sind das zusammen?', answerPrompt: 'Anzahl Teile:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [4, 8], a: [4, 4], b: [2, 2] } },
    { id: 'n27', text: 'Du trainierst {n} mal pro Woche. Jedes Training besteht aus {a} min Laufen und {b} min Kraftübungen. Wie viele Minuten trainierst du pro Woche insgesamt?', answerPrompt: 'Minuten:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [2, 4], a: [20, 30], b: [15, 20] } },
    { id: 'n28', text: 'Ein Zaun besteht aus {n} Elementen. Jedes Element hat {a} Latten und {b} Pfosten. Wie viele Holzteile sind insgesamt verbaut?', answerPrompt: 'Holzteile:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [5, 12], a: [8, 12], b: [1, 2] } },
    { id: 'n29', text: 'Für einen Ausflug bezahlen {n} Kinder. Die Fahrt kostet {a} Fr. und der Eintritt {b} Fr. pro Kind. Wie viel Geld sammelt der Lehrer ein?', answerPrompt: 'Summe:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [15, 25], a: [10, 15], b: [5, 8] } },
    { id: 'n30', text: 'Du nähst {n} Kissenbezüge. Pro Bezug brauchst du {a} cm Stoff und {b} cm Reißverschluss. Wie viele cm Material sind das insgesamt?', answerPrompt: 'Gesamtlänge:', formula: (v) => v.n * (v.a + v.b), ranges: { n: [2, 5], a: [40, 60], b: [30, 40] } },

    // --- 4. Verteilung / Durchschnitt: (A + B) / C ---
    { id: 'n31', text: 'Du und dein Bruder haben gespart. Du hast {a} Fr., dein Bruder hat {b} Fr. Ihr werft alles zusammen und kauft {n} gleich teure Geschenke davon. Wie viel kostet ein Geschenk?', answerPrompt: 'Preis pro Geschenk:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [20, 50], b: [20, 50], n: [2, 5] } },
    { id: 'n32', text: 'Bei einem Spendenlauf kamen {a} Fr. von der Klasse 4a und {b} Fr. von der Klasse 4b zusammen. Das Geld wird gerecht auf {n} Projekte verteilt. Wie viel bekommt jedes Projekt?', answerPrompt: 'Spende:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [100, 200], b: [100, 200], n: [2, 4] } },
    { id: 'n33', text: 'Für eine Bowle mischst du {a} Liter Saft mit {b} Liter Wasser. Das Getränk füllst du gleichmäßig in {n} Kannen ab. Wie viel Liter sind in jeder Kanne?', answerPrompt: 'Liter pro Kanne:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [2, 4], b: [2, 4], n: [2, 4] } },
    { id: 'n34', text: 'In einer Klasse sind {a} Jungen und {b} Mädchen. Für den Sport werden {n} gleich große Mannschaften gebildet. Wie viele Kinder sind in einer Mannschaft?', answerPrompt: 'Spieleranzahl:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [10, 14], b: [10, 14], n: [4, 6] } },
    { id: 'n35', text: 'Ein Bauer erntet {a} kg Äpfel und {b} kg Birnen. Er verpackt das gesamte Obst in {n} Kisten, die alle gleich schwer sind. Wie schwer ist eine Kiste?', answerPrompt: 'Gewicht:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [50, 100], b: [50, 100], n: [5, 10] } },
    { id: 'n36', text: 'Oma hat {a} rote und {b} blaue Perlen. Sie möchte daraus {n} völlig gleiche Ketten basteln. Wie viele Perlen kommen an jede Kette?', answerPrompt: 'Perlen pro Kette:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [20, 40], b: [20, 40], n: [2, 5] } },
    { id: 'n37', text: 'Beim Flohmarkt hast du {a} Fr. eingenommen, deine Schwester {b} Fr. Ihr teilt den gesamten Gewinn gerecht durch {n} (euch beide). Wie viel bekommt jeder?', answerPrompt: 'Gewinn pro Person:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [30, 60], b: [20, 50], n: [2, 2] } },
    { id: 'n38', text: 'Ein Buch hat {a} Textseiten und {b} Bildseiten. Du willst es in {n} Tagen komplett lesen. Wie viele Seiten musst du pro Tag schaffen?', answerPrompt: 'Seiten pro Tag:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [100, 150], b: [20, 50], n: [5, 10] } },
    { id: 'n39', text: 'Für den Bau einer Hütte brauchst du {a} lange und {b} kurze Bretter. Die Bretter werden in {n} Paketen geliefert. Wie viele Bretter sind in einem Paket, wenn alle gleich groß sind?', answerPrompt: 'Bretter pro Paket:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [10, 30], b: [10, 30], n: [2, 5] } },
    { id: 'n40', text: 'Im Stadion sind {a} Heimfans und {b} Gästefans. Nach dem Spiel verlassen sie das Stadion durch {n} Ausgänge. Wie viele Fans gehen durch jeden Ausgang, wenn sie sich gleichmäßig verteilen?', answerPrompt: 'Fans pro Ausgang:', formula: (v) => (v.a + v.b) / v.n, ranges: { a: [2000, 4000], b: [500, 1000], n: [4, 10] } },

    // --- 5. Rest nach Teilung: (A - B) / C ---
    { id: 'n41', text: 'Du hast {a} Fr. gespart. Davon kaufst du dir etwas für {b} Fr. Den Rest teilst du dir für die nächsten {n} Wochen als Taschengeld ein. Wie viel Geld hast du pro Woche zur Verfügung?', answerPrompt: 'Wochengeld:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [50, 100], b: [10, 20], n: [4, 8] } },
    { id: 'n42', text: 'Ein Seil ist {a} Meter lang. Ein kaputtes Stück von {b} Metern wird abgeschnitten. Der Rest wird in {n} gleiche Teile zerschnitten. Wie lang ist nun ein Teil?', answerPrompt: 'Länge:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [20, 50], b: [2, 5], n: [3, 6] } },
    { id: 'n43', text: 'In einer Kiste sind {a} Äpfel. {b} Äpfel sind faul und werden aussortiert. Die guten Äpfel werden gerecht an {n} Kinder verteilt. Wie viele Äpfel bekommt jedes Kind?', answerPrompt: 'Äpfel pro Kind:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [20, 40], b: [2, 8], n: [3, 6] } },
    { id: 'n44', text: 'Die Klasse hat {a} Fr. in der Klassenkasse. Für ein Abschiedsgeschenk werden {b} Fr. ausgegeben. Das restliche Geld wird an die {n} Schüler zurückgegeben. Wie viel bekommt jeder?', answerPrompt: 'Rückzahlung:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [100, 200], b: [20, 50], n: [10, 20] } },
    { id: 'n45', text: 'Ein Tank enthielt {a} Liter. {b} Liter wurden bereits verbraucht. Der Rest wird in {n} Kanister abgefüllt. Wie viel Liter kommen in einen Kanister?', answerPrompt: 'Liter pro Kanister:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [100, 200], b: [20, 80], n: [4, 8] } },
    { id: 'n46', text: 'Du hast {a} Sticker. {b} doppelte Sticker verschenkst du an Freunde. Die restlichen klebst du auf {n} Seiten in deinem Album. Wie viele Sticker kleben auf jeder Seite?', answerPrompt: 'Sticker pro Seite:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [50, 80], b: [10, 20], n: [4, 6] } },
    { id: 'n47', text: 'Ein Buch hat {a} Seiten. Die ersten {b} Seiten hast du schon gelesen. Den Rest willst du in {n} Tagen schaffen. Wie viele Seiten musst du pro Tag lesen?', answerPrompt: 'Tagespensum:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [150, 250], b: [30, 70], n: [4, 9] } },
    { id: 'n48', text: 'Zum Backen hast du {a} g Mehl abgewogen. Leider fallen {b} g auf den Boden. Den Rest teilst du auf {n} Schüsseln auf. Wie viel Mehl ist in jeder Schüssel?', answerPrompt: 'Mehlmenge:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [400, 600], b: [20, 50], n: [2, 4] } },
    { id: 'n49', text: 'Ein Arbeiter verdient {a} Fr. Davon werden {b} Fr. für Steuern abgezogen. Den Rest teilt er sich für {n} Wochen ein. Wie viel Geld hat er pro Woche?', answerPrompt: 'Wochenbudget:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [2000, 4000], b: [400, 800], n: [4, 4] } },
    { id: 'n50', text: 'In einem Saal sind insgesamt {a} Plätze. {b} Plätze sind defekt. Die nutzbaren Plätze sind in {n} Reihen angeordnet. Wie viele Plätze hat eine Reihe?', answerPrompt: 'Sitze pro Reihe:', formula: (v) => (v.a - v.b) / v.n, ranges: { a: [100, 200], b: [10, 20], n: [5, 10] } }
  ],

  advanced: [
    // --- 1. Kettenrechnung: A + B * C - D ---
    { id: 'a1', text: 'In der Kasse liegen zu Beginn {a} Fr. Es kommen {n} Kunden, die jeweils {b} Fr. bezahlen. Danach musst du einem Lieferanten {c} Fr. auszahlen. Wie viel Geld ist am Ende in der Kasse?', answerPrompt: 'Kassenbestand:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [100, 200], n: [3, 8], b: [10, 20], c: [20, 50] } },
    { id: 'a2', text: 'Der Wasserspiegel im Teich ist bei {a} cm. Es regnet {n} Stunden lang, wobei der Pegel um {b} cm pro Stunde steigt. Danach verdunsten {c} cm wieder durch die Sonne. Wie hoch ist der Pegel jetzt?', answerPrompt: 'Wasserstand:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [50, 80], n: [2, 5], b: [2, 5], c: [5, 10] } },
    { id: 'a3', text: 'Ein Lager hat {a} Kisten Vorrat. Ein LKW bringt {n} Paletten mit je {b} neuen Kisten. Danach werden {c} Kisten an Kunden verkauft. Wie viele Kisten sind noch übrig?', answerPrompt: 'Lagerbestand:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [50, 100], n: [3, 6], b: [10, 15], c: [20, 40] } },
    { id: 'a4', text: 'Dein Punktestand im Spiel beträgt {a} Punkte. Du schaffst {n} weitere Level, die dir jeweils {b} Punkte bringen. Durch einen Fehler verlierst du danach {c} Punkte. Wie viele Punkte hast du jetzt?', answerPrompt: 'Score:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [100, 200], n: [4, 8], b: [10, 20], c: [30, 50] } },
    { id: 'a5', text: 'Ein Turm ist {a} Meter hoch. Bauarbeiter setzen {n} neue Teile auf, die jeweils {b} Meter hoch sind. Der Turm sinkt jedoch um {c} Meter im weichen Boden ein. Wie hoch ragt er nun auf?', answerPrompt: 'Höhe:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [20, 40], n: [2, 5], b: [3, 5], c: [1, 2] } },
    { id: 'a6', text: 'Du hast {a} Fr. auf dem Konto. Du sparst {n} Monate lang jeweils {b} Fr. dazu. Dann kaufst du ein Fahrrad für {c} Fr. Wie viel Geld ist noch auf dem Konto?', answerPrompt: 'Kontostand:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [50, 100], n: [3, 6], b: [20, 30], c: [80, 120] } },
    { id: 'a7', text: 'Ein Buch hat ursprünglich {a} Seiten. Der Autor schreibt {n} neue Kapitel mit je {b} Seiten dazu. Der Verlag streicht am Ende aber {c} Seiten weg. Wie viele Seiten hat das Buch jetzt?', answerPrompt: 'Seitenanzahl:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [150, 200], n: [5, 10], b: [10, 15], c: [20, 40] } },
    { id: 'a8', text: 'Eine Hantelstange wiegt {a} kg. Du packst {n} Gewichte à {b} kg dazu. Dann nimmst du eine Scheibe von {c} kg wieder weg. Wie schwer ist die Hantel jetzt?', answerPrompt: 'Gewicht:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [20, 40], n: [2, 4], b: [5, 10], c: [2, 5] } },
    { id: 'a9', text: 'Die Temperatur beträgt {a} Grad. Sie steigt {n} Stunden lang um je {b} Grad. Nachts fällt sie dann um {c} Grad. Wie warm ist es am nächsten Morgen?', answerPrompt: 'Temperatur:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [10, 15], n: [3, 6], b: [2, 3], c: [5, 10] } },
    { id: 'a10', text: 'In einem Bus sitzen {a} Fahrgäste. An {n} Haltestellen steigen jeweils {b} weitere Personen ein. Danach steigen {c} Personen aus. Wie viele Fahrgäste sind jetzt noch im Bus?', answerPrompt: 'Personen:', formula: (v) => v.a + v.n * v.b - v.c, ranges: { a: [5, 10], n: [2, 4], b: [3, 5], c: [5, 10] } },

    // --- 2. Summe von Produkten: n * A + m * B ---
    { id: 'a11', text: 'Du kaufst {n} Äpfel für je {a} Rp. und {m} Birnen für je {b} Rp. Wie viel musst du an der Kasse insgesamt bezahlen?', answerPrompt: 'Preis (Rp):', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [3, 6], a: [40, 60], m: [2, 5], b: [50, 70] } },
    { id: 'a12', text: 'Im Kino bezahlen {n} Erwachsene je {a} Fr. Eintritt und {m} Kinder je {b} Fr. Eintritt. Wie hoch sind die gesamten Einnahmen an der Kasse?', answerPrompt: 'Einnahmen:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [2, 5], a: [15, 18], m: [3, 6], b: [8, 12] } },
    { id: 'a13', text: 'Ein Restaurant hat {n} Tische mit je {a} Stühlen und {m} Tische mit je {b} Stühlen. Wie viele Stühle gibt es insgesamt im Restaurant?', answerPrompt: 'Anzahl Stühle:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [4, 8], a: [4, 4], m: [2, 5], b: [6, 8] } },
    { id: 'a14', text: 'Bei einem Quiz gibt es für {n} schwere Fragen jeweils {a} Punkte und für {m} leichte Fragen jeweils {b} Punkte. Wie viele Punkte hast du insgesamt gesammelt?', answerPrompt: 'Gesamtpunkte:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [2, 5], a: [10, 20], m: [5, 10], b: [2, 5] } },
    { id: 'a15', text: 'Ein LKW transportiert {n} große Kisten, die je {a} kg wiegen, und {m} kleine Kisten mit je {b} kg. Wie schwer ist die gesamte Ladung?', answerPrompt: 'Gesamtgewicht:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [3, 6], a: [50, 100], m: [5, 10], b: [10, 20] } },
    { id: 'a16', text: 'Im Bücherregal stehen {n} dicke Bücher mit je {a} Seiten und {m} dünne Bücher mit je {b} Seiten. Wie viele Seiten sind das zusammen?', answerPrompt: 'Seitenanzahl:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [3, 5], a: [300, 500], m: [5, 10], b: [50, 100] } },
    { id: 'a17', text: 'Du kaufst {n} Packungen Kaugummi mit je {a} Stück und {m} Rollen Bonbons mit je {b} Stück. Wie viele Süßigkeiten hast du insgesamt?', answerPrompt: 'Anzahl:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [2, 5], a: [10, 12], m: [2, 4], b: [10, 15] } },
    { id: 'a18', text: 'Für ein Bauprojekt brauchst du {n} lange Balken von je {a} m Länge und {m} kurze Balken von je {b} m Länge. Wie viel Meter Holz ist das insgesamt?', answerPrompt: 'Holzlänge:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [4, 8], a: [4, 6], m: [5, 10], b: [2, 3] } },
    { id: 'a19', text: 'Ein Bauer hat {n} Kühe, die je {a} Liter Milch geben, und {m} Ziegen, die je {b} Liter Milch geben. Wie viel Milch hat er am Abend insgesamt?', answerPrompt: 'Liter Milch:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [5, 10], a: [15, 20], m: [5, 10], b: [2, 4] } },
    { id: 'a20', text: 'In einem Parkhaus parken Autos insgesamt {n} Stunden für je {a} Fr. pro Stunde. Motorräder parken {m} Stunden für je {b} Fr. pro Stunde. Wie hoch sind die Gesamteinnahmen?', answerPrompt: 'Summe:', formula: (v) => v.n * v.a + v.m * v.b, ranges: { n: [10, 20], a: [2, 4], m: [5, 10], b: [1, 2] } },

    // --- 3. Rückgeld mit Mengen: C - (n*A + m*B) ---
    { id: 'a21', text: 'Du bezahlst mit einem {c}-Fr.-Schein. Du kaufst {n} Hefte zu je {a} Fr. und {m} Stifte zu je {b} Fr. Wie viel Rückgeld bekommst du?', answerPrompt: 'Rückgeld:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [50, 100], n: [2, 5], a: [2, 4], m: [2, 5], b: [1, 3] } },
    { id: 'a22', text: 'Ein Aufzug darf {c} kg tragen. Es steigen {n} Männer mit je {a} kg und {m} Kinder mit je {b} kg ein. Wie viel Gewicht darf noch zugeladen werden?', answerPrompt: 'Restgewicht:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [600, 1000], n: [3, 5], a: [80, 90], m: [2, 4], b: [30, 40] } },
    { id: 'a23', text: 'Du hast {c} Minuten Zeit für die Hausaufgaben. Für Mathe brauchst du {n} mal {a} Minuten, für Deutsch {m} mal {b} Minuten. Wie viel Freizeit bleibt dir noch?', answerPrompt: 'Freizeit:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [90, 120], n: [2, 3], a: [10, 15], m: [1, 2], b: [15, 20] } },
    { id: 'a24', text: 'Ein Tank fasst {c} Liter. Du füllst {n} Kanister zu je {a} Litern und {m} Flaschen zu je {b} Litern ab. Wie viel ist danach noch im Tank?', answerPrompt: 'Restmenge:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [100, 200], n: [2, 4], a: [10, 20], m: [5, 10], b: [1, 2] } },
    { id: 'a25', text: 'Dein Datenvolumen beträgt {c} MB. Du lädst {n} Lieder mit je {a} MB und {m} Bilder mit je {b} MB herunter. Wie viel MB sind noch frei?', answerPrompt: 'Freier Speicher:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [500, 1000], n: [5, 10], a: [4, 6], m: [10, 20], b: [2, 3] } },
    { id: 'a26', text: 'Du hast {c} Meter Stoff. Du nähst {n} Hosen, die je {a} m brauchen, und {m} Röcke, die je {b} m brauchen. Wie viel Stoff bleibt als Rest?', answerPrompt: 'Stoffrest:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [20, 50], n: [2, 4], a: [2, 3], m: [2, 4], b: [1, 2] } },
    { id: 'a27', text: 'Das Budget für die Party beträgt {c} Fr. Wir kaufen {n} Pizzen für je {a} Fr. und {m} Kisten Getränke für je {b} Fr. Wie viel Budget ist übrig?', answerPrompt: 'Restbudget:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [150, 200], n: [3, 5], a: [12, 15], m: [2, 4], b: [10, 20] } },
    { id: 'a28', text: 'Der Lagerplatz ist {c} m² groß. {n} Maschinen brauchen je {a} m² und {m} Werkbänke brauchen je {b} m². Wie viel Platz ist noch frei?', answerPrompt: 'Freier Platz:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [100, 200], n: [2, 4], a: [10, 15], m: [3, 5], b: [5, 8] } },
    { id: 'a29', text: 'Ein Kühlschrank hat {c} Liter Platz. Es werden {n} Flaschen à {a} Liter und {m} Dosen à {b} Liter hineingestellt. Wie viel Platz ist noch übrig?', answerPrompt: 'Restplatz:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [50, 100], n: [4, 8], a: [1, 2], m: [5, 10], b: [1, 1] } },
    { id: 'a30', text: 'Du hast einen Gutschein über {c} Fr. Du kaufst {n} Bücher zu je {a} Fr. und {m} Karten zu je {b} Fr. Welchen Restwert hat der Gutschein noch?', answerPrompt: 'Restwert:', formula: (v) => v.c - (v.n * v.a + v.m * v.b), ranges: { c: [80, 120], n: [2, 3], a: [15, 20], m: [3, 5], b: [2, 4] } },

    // --- 4. Erweiterte Klammer: (A - B) * C + D ---
    { id: 'a31', text: 'Ein Ticket kostet normalerweise {a} Fr. Dank eines Gutscheins zahlst du {b} Fr. weniger pro Ticket. Du kaufst {n} Tickets. Die Versandgebühr beträgt einmalig {c} Fr. Was kostet alles zusammen?', answerPrompt: 'Gesamtkosten:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { a: [20, 30], b: [2, 5], n: [2, 5], c: [5, 8] } },
    { id: 'a32', text: 'Du hast {n} Flaschen. Jede fasst eigentlich {a} ml, aber in jeder fehlen bereits {b} ml. Zusätzlich hast du noch ein volles Glas mit {c} ml. Wie viel Flüssigkeit hast du insgesamt?', answerPrompt: 'Gesamtmenge:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { a: [500, 1000], b: [50, 100], n: [2, 4], c: [200, 300] } },
    { id: 'a33', text: 'Du kaufst {n} reduzierte Spiele. Der Preis war {a} Fr., ist aber um {b} Fr. gesenkt worden. An der Kasse kaufst du noch eine Tüte für {c} Fr. Wie viel bezahlst du?', answerPrompt: 'Endpreis:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { a: [40, 60], b: [10, 20], n: [2, 3], c: [1, 2] } },
    { id: 'a34', text: 'Ein Arbeiter arbeitet {n} Stunden. Sein Lohn beträgt {a} Fr. pro Stunde, aber davon werden {b} Fr. pro Stunde für Essen abgezogen. Am Ende kriegt er noch {c} Fr. Bonus. Wie hoch ist sein Verdienst?', answerPrompt: 'Verdienst:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [5, 8], a: [25, 35], b: [5, 8], c: [20, 50] } },
    { id: 'a35', text: 'Es gibt {n} Kisten mit Äpfeln. Eine volle Kiste wiegt {a} kg, das Leergewicht der Kiste ({b} kg) muss aber abgezogen werden. Dazu kommen noch {c} kg lose Äpfel. Wie viel wiegen die Äpfel allein?', answerPrompt: 'Apfelgewicht:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [5, 10], a: [15, 20], b: [2, 3], c: [5, 10] } },
    { id: 'a36', text: 'Du hast {n} Gutscheine. Jeder Gutschein ist {a} Fr. wert, aber bei der Einlösung werden {b} Fr. Gebühr abgezogen. Zusätzlich hast du {c} Fr. Bargeld. Wie viel Geld hast du insgesamt zur Verfügung?', answerPrompt: 'Gesamtgeld:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [3, 5], a: [20, 50], b: [5, 10], c: [10, 20] } },
    { id: 'a37', text: 'Ein Zug hat {n} Waggons. Jeder Waggon hat {a} Plätze, aber {b} davon sind jeweils defekt. Im Speisewagen gibt es zusätzlich {c} Plätze. Wie viele Plätze gibt es im ganzen Zug?', answerPrompt: 'Sitzplätze:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [5, 8], a: [60, 80], b: [2, 5], c: [20, 30] } },
    { id: 'a38', text: 'Du bastelst {n} Ketten. Jede sollte {a} Perlen haben, du machst sie aber um {b} Perlen kürzer. Am Ende hast du noch {c} einzelne Perlen übrig. Wie viele Perlen hast du insgesamt?', answerPrompt: 'Perlen:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [3, 6], a: [20, 30], b: [2, 5], c: [5, 10] } },
    { id: 'a39', text: 'Ein Bauer hat {n} Felder. Jedes bringt {a} kg Ertrag, wovon jedoch {b} kg als Verlust durch Vögel wegfallen. Im Lager liegen noch {c} kg aus dem Vorjahr. Wie viel Ertrag hat er insgesamt?', answerPrompt: 'Gesamtertrag:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [2, 4], a: [100, 200], b: [10, 20], c: [50, 100] } },
    { id: 'a40', text: 'Du sparst {n} Monate lang. Jeden Monat bekommst du {a} Fr., gibst aber sofort {b} Fr. davon aus. Zu Beginn hattest du schon {c} Fr. Wie viel hast du jetzt?', answerPrompt: 'Sparsumme:', formula: (v) => (v.a - v.b) * v.n + v.c, ranges: { n: [4, 8], a: [20, 30], b: [5, 10], c: [50, 80] } },

    // --- 5. Division komplexer: (A * B + C) / D ---
    { id: 'a41', text: 'Du hast {n} Tüten mit je {a} Bonbons. Dazu kommen {b} einzelne Bonbons. Du teilst alles gerecht auf {c} Kinder auf. Wie viele Bonbons bekommt jedes Kind?', answerPrompt: 'Bonbons pro Kind:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [3, 5], a: [10, 20], b: [5, 15], c: [3, 5] } },
    { id: 'a42', text: 'Ein Bauer erntet {n} Kisten Kartoffeln zu je {a} kg. Dazu sammelt er {b} kg lose Kartoffeln. Er verteilt alles gleichmäßig auf {c} Anhänger. Wie viel kg kommen auf jeden Anhänger?', answerPrompt: 'Gewicht pro Hänger:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [5, 10], a: [20, 40], b: [10, 50], c: [2, 5] } },
    { id: 'a43', text: 'In der Bibliothek sind {n} Regale mit je {a} Büchern. Auf dem Tisch liegen noch {b} Bücher. Alle Bücher werden in {c} Kisten verpackt. Wie viele Bücher kommen in eine Kiste?', answerPrompt: 'Bücher pro Kiste:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [4, 6], a: [20, 30], b: [10, 20], c: [2, 4] } },
    { id: 'a44', text: 'Du hast {n} Wochen lang jeweils {a} Fr. gespart. Oma schenkt dir noch {b} Fr. dazu. Du kaufst dir vom gesamten Geld {c} gleich teure Spiele. Was kostet ein Spiel?', answerPrompt: 'Preis pro Spiel:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [4, 8], a: [5, 10], b: [20, 40], c: [2, 4] } },
    { id: 'a45', text: 'Ein LKW fährt {n} mal eine Strecke von {a} km. Danach fährt er noch eine Strecke von {b} km. Der Fahrer teilt die Gesamtstrecke auf {c} Tage auf. Wie viele km fährt er pro Tag?', answerPrompt: 'Strecke pro Tag:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [3, 5], a: [100, 200], b: [50, 100], c: [2, 5] } },
    { id: 'a46', text: 'Für ein Fest werden {n} Tische mit je {a} Stühlen gestellt. {b} Reservestühle kommen noch dazu. Alle Stühle werden auf {c} Räume verteilt. Wie viele Stühle kommen in jeden Raum?', answerPrompt: 'Stühle pro Raum:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [10, 20], a: [6, 8], b: [10, 30], c: [2, 5] } },
    { id: 'a47', text: 'Du sammelst {n} Eimer Beeren. In jedem Eimer sind {a} Gramm. Dazu findest du noch {b} Gramm extra. Du machst daraus {c} Gläser Marmelade. Wie viel Gramm Beeren sind in einem Glas?', answerPrompt: 'Inhalt pro Glas:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [2, 4], a: [500, 1000], b: [100, 500], c: [5, 10] } },
    { id: 'a48', text: 'Es gibt {n} Klassen mit je {a} Schülern. Dazu kommen {b} Lehrer. Alle Personen fahren in {c} Bussen. Wie viele Personen sitzen in einem Bus?', answerPrompt: 'Personen pro Bus:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [3, 5], a: [20, 25], b: [5, 10], c: [2, 3] } },
    { id: 'a49', text: 'Ein Läufer läuft {n} Runden zu je {a} Metern. Dann sprintet er noch {b} Meter. Die Gesamtstrecke lief er in {c} Minuten. Wie viele Meter lief er pro Minute?', answerPrompt: 'Geschwindigkeit:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [4, 8], a: [400, 400], b: [100, 200], c: [10, 20] } },
    { id: 'a50', text: 'Ein Team macht Gewinn aus {n} Verkäufen zu je {a} Fr. Dazu kommen {b} Fr. Trinkgeld. Das gesamte Geld teilen sich die {c} Verkäufer. Wie viel bekommt jeder?', answerPrompt: 'Anteil:', formula: (v) => (v.n * v.a + v.b) / v.c, ranges: { n: [5, 10], a: [20, 50], b: [10, 50], c: [2, 4] } }
  ],

  profi: [
    // --- 1. Verschachtelung: A - ((B + C) * D) ---
    { id: 'p1', text: 'Du hast {a} Fr. gespart. Du möchtest {n} Sets kaufen. Jedes Set besteht aus einem Buch für {b} Fr. und einem Stift für {c} Fr. Wie viel Geld hast du nach dem Einkauf noch?', answerPrompt: 'Restgeld:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [200, 300], n: [2, 5], b: [15, 25], c: [2, 5] } },
    { id: 'p2', text: 'Ein LKW darf {a} kg laden. Er lädt {n} Paletten. Auf jeder Palette stehen eine Kiste mit {b} kg und ein Sack mit {c} kg. Wie viel Gewicht darf noch zugeladen werden?', answerPrompt: 'Freies Gewicht:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [1000, 2000], n: [5, 10], b: [50, 80], c: [20, 40] } },
    { id: 'p3', text: 'In einem Wassertank sind {a} Liter. {n} mal am Tag werden für die Tiere {b} Liter und für den Garten {c} Liter entnommen. Wie viel Wasser bleibt nach einem Tag im Tank?', answerPrompt: 'Restwasser:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [500, 800], n: [2, 4], b: [20, 50], c: [30, 60] } },
    { id: 'p4', text: 'Dein Datenvolumen beträgt {a} MB. Du lädst {n} Musikalben herunter. Jedes Album besteht aus {b} MB Musik und {c} MB Coverbildern. Wie viel Speicher ist danach noch frei?', answerPrompt: 'Freier Speicher:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [1000, 2000], n: [5, 10], b: [50, 80], c: [5, 10] } },
    { id: 'p5', text: 'Du hast {a} Punkte im Spiel. In {n} Runden verlierst du jeweils {b} Punkte durch Zeitüberschreitung und {c} Punkte durch Fehler. Wie ist dein Endstand?', answerPrompt: 'Punkte:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [500, 800], n: [3, 6], b: [10, 20], c: [5, 15] } },
    { id: 'p6', text: 'Ein Stoffballen hat {a} Meter. Die Schneiderin näht {n} Kostüme. Für jedes braucht sie {b} Meter Oberstoff und {c} Meter Futterstoff vom gleichen Ballen. Wie viel Meter bleiben übrig?', answerPrompt: 'Reststoff:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [50, 100], n: [3, 5], b: [2, 4], c: [1, 2] } },
    { id: 'p7', text: 'Das Budget beträgt {a} Fr. Wir kaufen für {n} Mitarbeiter Arbeitskleidung. Jeder bekommt eine Hose für {b} Fr. und eine Jacke für {c} Fr. Wie viel Budget bleibt übrig?', answerPrompt: 'Restbudget:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [1000, 2000], n: [5, 10], b: [40, 60], c: [50, 80] } },
    { id: 'p8', text: 'Ein Seil ist {a} cm lang. Du schneidest {n} Stücke ab. Bei jedem Schnitt brauchst du {b} cm für das Stück selbst und hast {c} cm Verschnitt. Wie viel Seil ist noch auf der Rolle?', answerPrompt: 'Restseil:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [200, 500], n: [4, 8], b: [20, 30], c: [2, 5] } },
    { id: 'p9', text: 'Dein Startkapital beträgt {a} Fr. In den nächsten {n} Monaten hast du monatliche Ausgaben für das Handy ({b} Fr.) und den Sportverein ({c} Fr.). Wie viel ist nach dieser Zeit noch übrig?', answerPrompt: 'Restkapital:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [500, 800], n: [3, 6], b: [15, 25], c: [20, 40] } },
    { id: 'p10', text: 'Im Silo sind {a} kg Getreide. Der Bauer füllt {n} Säcke mit einer Mischung ab. In jeden Sack kommen {b} kg Weizen und {c} kg Gerste aus dem Silo. Wie viel kg bleiben im Silo?', answerPrompt: 'Restmenge:', formula: (v) => v.a - (v.b + v.c) * v.n, ranges: { a: [1000, 2000], n: [10, 20], b: [20, 30], c: [10, 20] } },

    // --- 2. Verschachtelung: (A - (B * C)) / D ---
    { id: 'p11', text: 'Du hast {a} Fr. Du kaufst {b} Hefte für je {c} Fr. Den Rest des Geldes teilst du dir für die nächsten {n} Wochen ein. Wie viel hast du pro Woche?', answerPrompt: 'Wochengeld:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [100, 200], b: [5, 10], c: [2, 5], n: [4, 8] } },
    { id: 'p12', text: 'Ein Tank hat {a} Liter. Eine Pumpe saugt {b} Minuten lang {c} Liter pro Minute ab. Der Rest wird auf {n} Fässer verteilt. Wie viel Inhalt kommt in ein Fass?', answerPrompt: 'Liter pro Fass:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [500, 1000], b: [10, 20], c: [10, 20], n: [5, 10] } },
    { id: 'p13', text: 'Im Lagerbestand sind {a} Stück. Ein Kunde kauft {b} Kartons mit je {c} Stück. Der Rest wird in {n} Regale einsortiert. Wie viele Stück kommen in jedes Regal?', answerPrompt: 'Stückzahl:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [500, 800], b: [10, 20], c: [10, 20], n: [4, 8] } },
    { id: 'p14', text: 'Du hast {a} Sticker. Du schenkst {b} Freunden je {c} Sticker. Die restlichen Sticker klebst du auf {n} Seiten in dein Album. Wie viele Sticker kommen auf eine Seite?', answerPrompt: 'Sticker pro Seite:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [100, 200], b: [3, 5], c: [5, 10], n: [5, 10] } },
    { id: 'p15', text: 'Ein Kabel ist {a} cm lang. Der Elektriker schneidet {b} Stücke mit je {c} cm ab. Den Rest teilt er in {n} kleine Stücke. Wie lang ist ein kleines Stück?', answerPrompt: 'Länge:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [500, 800], b: [5, 10], c: [20, 40], n: [5, 10] } },
    { id: 'p16', text: 'Der Gewinn beträgt {a} Fr. Davon müssen noch {b} Stundenlöhne zu je {c} Fr. bezahlt werden. Der Restgewinn wird an {n} Partner verteilt. Wie viel bekommt jeder?', answerPrompt: 'Anteil:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [2000, 4000], b: [10, 20], c: [50, 80], n: [2, 4] } },
    { id: 'p17', text: 'Ein Buch hat {a} Seiten. Du liest {b} Tage lang je {c} Seiten. Den Rest willst du in {n} Tagen schaffen. Wie viele Seiten musst du dann pro Tag lesen?', answerPrompt: 'Seiten pro Tag:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [300, 500], b: [5, 10], c: [10, 20], n: [5, 10] } },
    { id: 'p18', text: 'Der Futtervorrat beträgt {a} kg. {b} Pferde fressen jeweils {c} kg. Der Rest wird auf {n} Säcke verteilt. Wie schwer ist ein Sack?', answerPrompt: 'Gewicht:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [200, 400], b: [2, 5], c: [10, 20], n: [4, 8] } },
    { id: 'p19', text: 'Du hast ein Startkapital von {a} Punkten. Wegen {b} Fehlern werden dir je {c} Strafpunkte abgezogen. Die verbleibenden Punkte werden durch {n} geteilt (Bonus-Rechnung). Was ist das Ergebnis?', answerPrompt: 'Wert:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [100, 200], b: [2, 5], c: [5, 10], n: [2, 5] } },
    { id: 'p20', text: 'Ein Feld ist {a} m² groß. {b} Beete mit je {c} m² sind schon belegt. Die freie Fläche wird in {n} gleich große Parzellen geteilt. Wie groß ist eine Parzelle?', answerPrompt: 'Fläche:', formula: (v) => (v.a - v.b * v.c) / v.n, ranges: { a: [500, 1000], b: [5, 10], c: [10, 20], n: [4, 8] } },

    // --- 3. Verschachtelung: (A + (B * C)) / D ---
    { id: 'p21', text: 'Du hast {a} Fr. gespart. Dazu verdienst du {b} Wochen lang je {c} Fr. Dein gesamtes Geld teilst du auf {n} Sparkonten auf. Wie viel kommt auf jedes Konto?', answerPrompt: 'Betrag:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [50, 100], b: [4, 8], c: [10, 20], n: [2, 4] } },
    { id: 'p22', text: 'Im Lager sind {a} Reifen. Eine Lieferung bringt {b} Paletten mit je {c} Reifen. Alle Reifen werden auf {n} Autos montiert (je 4 Reifen pro Auto). Wie viele Autos können bestückt werden? (Setze n=4)', answerPrompt: 'Anzahl Autos:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [20, 40], b: [5, 10], c: [4, 8], n: [4, 4] } },
    { id: 'p23', text: 'Ein Weg ist schon {a} Meter lang. Er wird um {b} Teilstücke verlängert, die je {c} Meter lang sind. Die Gesamtlänge wird in {n} Abschnitte unterteilt. Wie lang ist ein Abschnitt?', answerPrompt: 'Länge:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [10, 20], b: [5, 10], c: [2, 5], n: [4, 8] } },
    { id: 'p24', text: 'Ein Behälter wiegt leer {a} g. Du füllst {b} Kugeln hinein, die je {c} g wiegen. Das Gesamtgewicht wird durch {n} geteilt. Was ist das Ergebnis?', answerPrompt: 'Gewichtswert:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [100, 200], b: [5, 10], c: [20, 50], n: [2, 5] } },
    { id: 'p25', text: 'In Runde 1 hast du {a} Punkte. In Runde 2 erzielst du {b} Treffer für je {c} Punkte. Es wird der Durchschnitt aus {n} Spielen berechnet (hier n=2). Wie hoch ist der Durchschnitt?', answerPrompt: 'Durchschnitt:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [50, 100], b: [5, 10], c: [5, 10], n: [2, 2] } },
    { id: 'p26', text: 'In der Kasse sind {a} Fr. Dazu kommen Einnahmen aus {b} Verkäufen zu je {c} Fr. Das gesamte Geld wird in {n} Geldbeutel sortiert. Wie viel kommt in jeden Beutel?', answerPrompt: 'Betrag:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [100, 200], b: [10, 20], c: [5, 10], n: [2, 5] } },
    { id: 'p27', text: 'Dein Schulweg ist {a} km lang. Dazu fährst du noch {b} mal pro Woche zum Sport, was jeweils {c} km sind. Die Gesamtstrecke fährst du an {n} Tagen. Wie viele km sind das pro Tag?', answerPrompt: 'Km pro Tag:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [20, 50], b: [2, 5], c: [5, 10], n: [2, 5] } },
    { id: 'p28', text: 'Im Beet blühen {a} Blumen. Dazu werden noch {b} Reihen mit je {c} neuen Blumen gepflanzt. Alle Blumen werden für {n} Sträuße gepflückt. Wie viele Blumen kommen in einen Strauß?', answerPrompt: 'Anzahl:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [20, 40], b: [4, 8], c: [5, 10], n: [5, 10] } },
    { id: 'p29', text: 'Die Grundgebühr für den Platz beträgt {a} Fr. Dazu kommen {b} Stunden Nutzung zu je {c} Fr. Die Gesamtkosten teilen sich {n} Freunde. Wie viel muss jeder zahlen?', answerPrompt: 'Kosten pro Person:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [20, 50], b: [2, 5], c: [5, 10], n: [2, 4] } },
    { id: 'p30', text: 'Ein LKW wiegt leer {a} kg. Die Ladung besteht aus {b} Kisten zu je {c} kg. Das Gesamtgewicht verteilt sich auf {n} Achsen. Wie hoch ist die Last pro Achse?', answerPrompt: 'Achslast:', formula: (v) => (v.a + v.b * v.c) / v.n, ranges: { a: [2000, 4000], b: [10, 20], c: [50, 100], n: [2, 4] } },

    // --- 4. Verschachtelung: A - (B / C) oder komplexer ---
    { id: 'p31', text: 'Du besitzt {a} Fr. Du kaufst ein Gerät für {b} Fr., zahlst es aber in {c} Raten ab. Wie viel Geld hast du noch übrig, nachdem du die erste Rate bezahlt hast?', answerPrompt: 'Restgeld:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [100, 200], b: [100, 200], c: [2, 5] } },
    { id: 'p32', text: 'Eine Wanderung ist {a} km lang. Ein Teilstück von {b} km soll in {c} Tagen gewandert werden. Wie viele km fehlen noch zur Gesamtstrecke, nachdem du das Pensum eines Tages geschafft hast?', answerPrompt: 'Reststrecke:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [50, 100], b: [20, 40], c: [2, 4] } },
    { id: 'p33', text: 'Du hast {a} Fr. Guthaben. Ein Anruf kostet normalerweise {b} Fr., aber heute zahlst du nur den {c}-ten Teil davon. Wie viel Guthaben hast du nach einem Anruf noch?', answerPrompt: 'Restguthaben:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [50, 80], b: [20, 40], c: [2, 4] } },
    { id: 'p34', text: 'Du hast {a} min Zeit. Eine Aufgabe dauert normalerweise {b} min, aber du bist schneller und brauchst nur den {c}-ten Teil der Zeit. Wie viel Zeit bleibt dir nach der Aufgabe?', answerPrompt: 'Restzeit:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [60, 120], b: [20, 30], c: [2, 5] } },
    { id: 'p35', text: 'Auf der Waage liegen {a} kg. Ein Paket von {b} kg wird in {c} Teile geteilt, und einer dieser Teile wird von der Waage weggenommen. Welches Gewicht zeigt sie jetzt?', answerPrompt: 'Gewicht:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [10, 20], b: [2, 6], c: [2, 2] } },
    { id: 'p36', text: 'Ein Spiel kostet {a} Fr. Es gibt einen Rabatt. Der Rabatt entspricht dem {c}-ten Teil von {b} Fr. Wie hoch ist der Endpreis?', answerPrompt: 'Preis:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [50, 100], b: [10, 20], c: [2, 5] } },
    { id: 'p37', text: 'Du hast einen Vorrat von {a}. Dein Verbrauch berechnet sich aus {b} geteilt durch {c}. Wie viel Vorrat hast du nach dem Verbrauch noch übrig?', answerPrompt: 'Rest:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [20, 30], b: [10, 20], c: [2, 5] } },
    { id: 'p38', text: 'Ein Band ist {a} m lang. Du schneidest ein Stück ab, dessen Länge dem {c}-tel von {b} m entspricht. Wie lang ist das Band jetzt?', answerPrompt: 'Länge:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [10, 20], b: [5, 10], c: [2, 5] } },
    { id: 'p39', text: 'Dein Guthaben beträgt {a} Fr. Die Gebühr, die abgezogen wird, beträgt {b} Fr. geteilt durch {c}. Wie hoch ist dein neuer Kontostand?', answerPrompt: 'Stand:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [100, 200], b: [10, 20], c: [2, 5] } },
    { id: 'p40', text: 'Die Temperatur beträgt {a} Grad. Sie sinkt um einen Wert, der {b} geteilt durch {c} entspricht. Wie warm ist es danach?', answerPrompt: 'Temperatur:', formula: (v) => v.a - (v.b / v.c), ranges: { a: [20, 30], b: [5, 10], c: [2, 5] } },

    // --- 5. Komplexe Mischung ---
    { id: 'p41', text: 'Ein Kino hat {a} Plätze. Es sind {b} Reihen mit je {c} Zuschauern belegt. Außerdem sind {n} Plätze defekt und können nicht genutzt werden. Wie viele Plätze sind noch frei?', answerPrompt: 'Freie Plätze:', formula: (v) => v.a - v.b * v.c - v.n, ranges: { a: [200, 300], b: [5, 10], c: [10, 15], n: [5, 10] } },
    { id: 'p42', text: 'Du hast {a} Fr. Du hast Ausgaben in Höhe von {b} mal {c} Fr. Danach nimmst du aber wieder {n} mal {c} Fr. ein. Wie viel Geld hast du am Ende?', answerPrompt: 'Endstand:', formula: (v) => v.a - v.b * v.c + v.n * v.c, ranges: { a: [100, 200], b: [2, 5], c: [5, 10], n: [2, 5] } },
    { id: 'p43', text: 'Eine Reise ist {a} km lang. Am ersten Tag fährst du {b} km. Am zweiten Tag fährst du {n} Etappen zu je {c} km. Wie viele km musst du noch fahren?', answerPrompt: 'Reststrecke:', formula: (v) => v.a - v.b - v.c * v.n, ranges: { a: [500, 800], b: [50, 100], c: [20, 40], n: [2, 4] } },
    { id: 'p44', text: 'Du arbeitest {n} Stunden. Dein Stundenlohn beträgt {a} Fr., aber {b} Fr. werden pro Stunde für Abgaben abgezogen. Am Ende erhältst du einen einmaligen Bonus von {c} Fr. Wie viel hast du insgesamt verdient?', answerPrompt: 'Lohn:', formula: (v) => v.n * (v.a - v.b) + v.c, ranges: { a: [25, 30], n: [30, 40], b: [5, 5], c: [50, 100] } },
    { id: 'p45', text: 'Es gibt {n} Paletten. Auf jeder Palette stehen {a} große und {b} kleine Kisten. Jede einzelne Kiste wiegt {c} kg. Wie schwer ist alles zusammen?', answerPrompt: 'Gesamtgewicht:', formula: (v) => v.n * (v.a + v.b) * v.c, ranges: { n: [2, 5], a: [5, 10], b: [5, 10], c: [2, 5] } },
    { id: 'p46', text: 'Der Eintritt kostet {a} Fr. Eine Gruppe besteht aus {n} Personen. Davon zahlen {b} Personen den vollen Preis, der Rest zahlt nur die Hälfte. Wie viel bezahlt die Gruppe insgesamt?', answerPrompt: 'Gesamtpreis:', formula: (v) => v.b * v.a + (v.n - v.b) * (v.a / 2), ranges: { a: [10, 20], n: [6, 10], b: [3, 5] } },
    { id: 'p47', text: 'Du kaufst {n} Hefte. Der Preis pro Heft ist {a} Fr., aber es gibt {b} Fr. Rabatt pro Heft. Du bezahlst mit einem {c}-Fr.-Schein. Wie viel Rückgeld bekommst du?', answerPrompt: 'Rückgeld:', formula: (v) => v.c - v.n * (v.a - v.b), ranges: { n: [2, 5], a: [5, 8], b: [1, 2], c: [50, 100] } },
    { id: 'p48', text: 'In einem Krug sind {a} Liter Saft. {n} Kinder trinken jeweils {b} Milliliter. Wie viele Liter Saft sind noch übrig?', answerPrompt: 'Liter:', formula: (v) => v.a - (v.n * v.b) / 1000, ranges: { a: [5, 10], n: [5, 10], b: [200, 300] } },
    { id: 'p49', text: 'Du fährst im Training {n} Runden. Jede Runde ist {a} km lang. Deine Geschwindigkeit beträgt {b} km/h. Wie viele Stunden brauchst du für die Strecke?', answerPrompt: 'Stunden:', formula: (v) => (v.n * v.a) / v.b, ranges: { n: [2, 4], a: [10, 20], b: [20, 40] } },
    { id: 'p50', text: 'Der Gewinn beträgt {a} Fr. Zuerst werden {b} Fr. als Rücklage abgezogen. Der Rest wird auf {n} Partner verteilt. Von diesem Anteil spendet jeder noch {c} Fr. Wie viel behält jeder Partner am Ende?', answerPrompt: 'Endbetrag:', formula: (v) => ((v.a - v.b) / v.n) - v.c, ranges: { a: [2000, 4000], b: [500, 1000], n: [2, 5], c: [50, 100] } }
  ]
};